//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoreData.Models.Mapping;

namespace CoreData.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSExternalLoginContext : DbContext
    {
        public BMSExternalLoginContext()
            : base("name=BMSExternalLoginContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new ExternalLoginMapping());
        }
    
        public virtual DbSet<VonageExternalLogin> VonageExternalLogins { get; set; }
    }
}
