//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreData.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class VonageExternalLogin
    {
        public int Id { get; set; }
        public Nullable<int> MerchantId { get; set; }
        public string MerchantPassword { get; set; }
        public string EncryptedToken { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
