// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class change_name_predifined_filters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_name_predifined_filters));
        
        string IMigrationMetadata.Id
        {
            get { return "201407092055297_change_name_predifined_filters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
