// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_index_on_filters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_index_on_filters));
        
        string IMigrationMetadata.Id
        {
            get { return "201406181828530_add_index_on_filters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
