// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class report_labels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(report_labels));
        
        string IMigrationMetadata.Id
        {
            get { return "201407231744184_report_labels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
