// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_usertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_usertype));
        
        string IMigrationMetadata.Id
        {
            get { return "201406271703445_add_usertype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
