// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_filter_option_definitions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_filter_option_definitions));
        
        string IMigrationMetadata.Id
        {
            get { return "201406181443133_add_filter_option_definitions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
