// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_field_name_to_predefined_filter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field_name_to_predefined_filter));
        
        string IMigrationMetadata.Id
        {
            get { return "201406181822596_add_field_name_to_predefined_filter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
