// <auto-generated />
namespace CoreData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class removing_rowversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removing_rowversion));
        
        string IMigrationMetadata.Id
        {
            get { return "201407011806260_removing_rowversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
