
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VirtualOffice.Data.EFModels
{

using System;
    using System.Collections.Generic;
    
public partial class C_account_register_merchant
{

    public int reg_pk { get; set; }

    public Nullable<int> MID { get; set; }

    public string merchantName { get; set; }

    public string transactionType { get; set; }

    public string description { get; set; }

    public Nullable<System.DateTime> transactionDate { get; set; }

    public string company { get; set; }

    public Nullable<decimal> debit { get; set; }

    public Nullable<decimal> credit { get; set; }

    public Nullable<decimal> accBalance { get; set; }

}

}
