//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOffice.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_acc_invoiceheader
    {
        public int inv_id { get; set; }
        public Nullable<System.DateTime> inv_date { get; set; }
        public Nullable<int> merchant_fk { get; set; }
        public Nullable<int> merchant_StoreNo { get; set; }
        public string merchant_businessname { get; set; }
        public string merchant_busphone { get; set; }
        public string merchant_busaddress { get; set; }
        public string merchant_addressCityID { get; set; }
        public string merchant_addressStateID { get; set; }
        public string merchant_addressZIP { get; set; }
        public string merchant_addressCountryID { get; set; }
        public Nullable<int> ach_status { get; set; }
        public Nullable<System.DateTime> ach_sentdate { get; set; }
        public Nullable<int> ach_id { get; set; }
        public Nullable<int> RepCommission_fk { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<System.DateTime> Posted_date { get; set; }
        public Nullable<int> Printed { get; set; }
        public Nullable<int> PrintedMonth { get; set; }
        public Nullable<int> PrintedYear { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> HoldNotesId { get; set; }
        public Nullable<bool> Hold { get; set; }
        public Nullable<int> Inv_Related { get; set; }
        public Nullable<System.DateTime> approx_PaidDate { get; set; }
        public Nullable<bool> GroupPrinted { get; set; }
        public Nullable<System.DateTime> GroupPrintedDate { get; set; }
        public int ComInvoice_fk { get; set; }
        public Nullable<int> ConfirmPaid { get; set; }
        public Nullable<System.DateTime> ConfirmPaidDate { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<decimal> Payments { get; set; }
        public string UserPaid { get; set; }
        public Nullable<int> DownInvoice { get; set; }
        public Nullable<int> ClubId { get; set; }
        public Nullable<System.DateTime> SpecialDate { get; set; }
        public Nullable<int> SpecialBilling { get; set; }
        public Nullable<int> SpecialActBilling { get; set; }
        public Nullable<int> inv_type { get; set; }
        public Nullable<int> inv_TermsId { get; set; }
        public Nullable<bool> inv_void { get; set; }
        public Nullable<int> waswriteoff { get; set; }
        public Nullable<decimal> amountwriteoff { get; set; }
        public string inv_comments { get; set; }
        public int inv_createdby { get; set; }
        public string merchant_shipto { get; set; }
        public string merchant_shipaddress1 { get; set; }
        public string merchant_shipaddress2 { get; set; }
        public string merchant_shipcity { get; set; }
        public string merchant_shipstate { get; set; }
        public string merchant_shipzip { get; set; }
        public string merchant_shipcountry { get; set; }
        public Nullable<int> POSARInvoiceID { get; set; }
        public Nullable<int> PortalAPInvoiceID { get; set; }
        public Nullable<System.DateTime> inv_voiddate { get; set; }
        public string inv_voidedby { get; set; }
        public Nullable<int> glID { get; set; }
        public Nullable<decimal> paymentscc { get; set; }
        public Nullable<decimal> paymentscash { get; set; }
        public Nullable<bool> inv_noSplit { get; set; }
        public Nullable<System.DateTime> flagcommCCDateI { get; set; }
        public Nullable<System.DateTime> flagcommCCDateF { get; set; }
        public Nullable<int> PinServeARInvID { get; set; }
        public Nullable<int> CompanyAPInvID { get; set; }
        public Nullable<bool> formerPOS { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> DistId { get; set; }
        public Nullable<int> MDistId { get; set; }
        public Nullable<System.DateTime> inv_timeStamp { get; set; }
        public Nullable<int> inv_tnb_llc { get; set; }
        public Nullable<decimal> VoidedBalance { get; set; }
        public Nullable<decimal> Voidedpayment { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<int> BillingType { get; set; }
        public Nullable<decimal> SRPTotal { get; set; }
        public Nullable<decimal> DiscountTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<int> IsManualInv { get; set; }
        public Nullable<decimal> ValueRecPlan { get; set; }
        public Nullable<decimal> Original_InvoiceAmount { get; set; }
        public Nullable<int> RecPlanDone { get; set; }
        public Nullable<int> percentdiscount { get; set; }
        public Nullable<int> mastercard { get; set; }
        public Nullable<int> giftcard { get; set; }
        public Nullable<int> isPlanC { get; set; }
        public Nullable<bool> prepay_statement_sent { get; set; }
        public Nullable<int> IsBadDebt { get; set; }
        public Nullable<int> midbaddebt { get; set; }
        public Nullable<bool> IsDtvPP { get; set; }
        public Nullable<int> original_merchant_fk { get; set; }
        public Nullable<int> original_inv_id { get; set; }
    }
}
