
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VirtualOffice.Data.EFModels
{

using System;
    using System.Collections.Generic;
    
public partial class DashboardConfig
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string ItemsFunction { get; set; }

    public string ImageUrl { get; set; }

    public string DashboardItemType { get; set; }

    public string Remark { get; set; }

    public string LinkUrl { get; set; }

}

}
