
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VirtualOffice.Data.EFModels
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int Id { get; set; }

    public byte[] RowVersion { get; set; }

    public System.DateTime TimeSpan { get; set; }

    public int UserId { get; set; }

    public int RefId { get; set; }



    public virtual User User { get; set; }

}

}
