//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOffice.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ReportLabels = new HashSet<ReportLabel>();
            this.ReportPredefinedFilterRels = new HashSet<ReportPredefinedFilterRel>();
            this.ReportToReportRels = new HashSet<ReportToReportRel>();
            this.ReportToReportRels1 = new HashSet<ReportToReportRel>();
            this.UserReports = new HashSet<UserReport>();
        }
    
        public int Id { get; set; }
        public string Query { get; set; }
        public bool IsEnable { get; set; }
        public System.DateTime TimeSpan { get; set; }
        public string Output { get; set; }
        public string Name { get; set; }
        public string DefaultOutput { get; set; }
        public byte[] RowVersion { get; set; }
        public string ParamsDefaultConfiguration { get; set; }
        public string UserFilters { get; set; }
        public string IndexColumnName { get; set; }
        public bool IsStandAlone { get; set; }
        public string Category { get; set; }
        public int Level { get; set; }
    
        public virtual ICollection<ReportLabel> ReportLabels { get; set; }
        public virtual ICollection<ReportPredefinedFilterRel> ReportPredefinedFilterRels { get; set; }
        public virtual ICollection<ReportToReportRel> ReportToReportRels { get; set; }
        public virtual ICollection<ReportToReportRel> ReportToReportRels1 { get; set; }
        public virtual ICollection<UserReport> UserReports { get; set; }
    }
}
