
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VirtualOffice.Data.EFModels
{

using System;
    using System.Collections.Generic;
    
public partial class Sql_HtmlTypeNameMappings
{

    public int Id { get; set; }

    public string SqlTypeName { get; set; }

    public string HtmlTypeName { get; set; }

}

}
