//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOffice.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.HashKeys = new HashSet<HashKey>();
            this.Orders = new HashSet<Order>();
            this.UserReports = new HashSet<UserReport>();
        }
    
        public int Id { get; set; }
        public int RefId { get; set; }
        public int Category { get; set; }
        public System.DateTime TimeSpan { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<HashKey> HashKeys { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<UserReport> UserReports { get; set; }
    }
}
