//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOffice.Data.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReport
    {
        public UserReport()
        {
            this.UserReportFilters = new HashSet<UserReportFilter>();
        }
    
        public int UserId { get; set; }
        public int ReportId { get; set; }
        public string Output { get; set; }
        public System.DateTime TimeSpan { get; set; }
        public byte[] RowVersion { get; set; }
        public string Name { get; set; }
        public string OutputConfiguration { get; set; }
        public int ExecutionCount { get; set; }
        public int RowCount { get; set; }
        public bool ShouldBeShownAtDesktop { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual ICollection<UserReportFilter> UserReportFilters { get; set; }
        public virtual User User { get; set; }
    }
}
