//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOffice.Data.EFModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VirtualOfficeEntities : DbContext
    {
        public VirtualOfficeEntities()
            : base("name=VirtualOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ApiUser> ApiUsers { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<DashboardConfig> DashboardConfigs { get; set; }
        public virtual DbSet<HashKey> HashKeys { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PredefinedFilter> PredefinedFilters { get; set; }
        public virtual DbSet<ReportLabel> ReportLabels { get; set; }
        public virtual DbSet<ReportLog> ReportLogs { get; set; }
        public virtual DbSet<ReportPredefinedFilterRel> ReportPredefinedFilterRels { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportToReportRel> ReportToReportRels { get; set; }
        public virtual DbSet<Sql_HtmlTypeNameMappings> Sql_HtmlTypeNameMappings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
        public virtual DbSet<UserReportFilter> UserReportFilters { get; set; }
        public virtual DbSet<UserReportFilterValue> UserReportFilterValues { get; set; }
        public virtual DbSet<UserReport> UserReports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<C_acc_invoiceheader> C_acc_invoiceheader { get; set; }
        public virtual DbSet<C_account_register> C_account_register { get; set; }
        public virtual DbSet<C_account_register_merchant> C_account_register_merchant { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
    
        public virtual ObjectResult<AccountsInCollection_Result> AccountsInCollection(Nullable<int> agentid, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AccountsInCollection_Result>("AccountsInCollection", agentidParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<get_agents_Result> get_agents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_agents_Result>("get_agents");
        }
    
        public virtual ObjectResult<get_system_logins_Result> get_system_logins(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_system_logins_Result>("get_system_logins", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetTodayTransactions_Result> GetTodayTransactions(Nullable<int> agentid, Nullable<int> merchantid, string iniDate, string endDate, string trxType_hyp_fk, string item_fk, Nullable<int> vendingType, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var trxType_hyp_fkParameter = trxType_hyp_fk != null ?
                new ObjectParameter("TrxType_hyp_fk", trxType_hyp_fk) :
                new ObjectParameter("TrxType_hyp_fk", typeof(string));
    
            var item_fkParameter = item_fk != null ?
                new ObjectParameter("item_fk", item_fk) :
                new ObjectParameter("item_fk", typeof(string));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTodayTransactions_Result>("GetTodayTransactions", agentidParameter, merchantidParameter, iniDateParameter, endDateParameter, trxType_hyp_fkParameter, item_fkParameter, vendingTypeParameter, emptyRecordParameter);
        }
    
        public virtual int SetStandAloneReportsOnDesktop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SetStandAloneReportsOnDesktop");
        }
    
        public virtual int SP_accountsInCollection(Nullable<int> agentid, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_accountsInCollection", agentidParameter, emptyRecordParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_get_marketing_materials_Result> sp_get_marketing_materials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_marketing_materials_Result>("sp_get_marketing_materials");
        }
    
        public virtual int Sp_get_Today_Transactions(Nullable<int> agentid, Nullable<int> merchantid, string iniDate, string endDate, string trxType_hyp_fk, string item_fk, Nullable<int> vendingType, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var trxType_hyp_fkParameter = trxType_hyp_fk != null ?
                new ObjectParameter("TrxType_hyp_fk", trxType_hyp_fk) :
                new ObjectParameter("TrxType_hyp_fk", typeof(string));
    
            var item_fkParameter = item_fk != null ?
                new ObjectParameter("item_fk", item_fk) :
                new ObjectParameter("item_fk", typeof(string));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_get_Today_Transactions", agentidParameter, merchantidParameter, iniDateParameter, endDateParameter, trxType_hyp_fkParameter, item_fkParameter, vendingTypeParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<Sp_GetMerchantStatement_Result> Sp_GetMerchantStatement(string merchant_fk, string dtmDateInit, string dtmDateEnd)
        {
            var merchant_fkParameter = merchant_fk != null ?
                new ObjectParameter("merchant_fk", merchant_fk) :
                new ObjectParameter("merchant_fk", typeof(string));
    
            var dtmDateInitParameter = dtmDateInit != null ?
                new ObjectParameter("dtmDateInit", dtmDateInit) :
                new ObjectParameter("dtmDateInit", typeof(string));
    
            var dtmDateEndParameter = dtmDateEnd != null ?
                new ObjectParameter("dtmDateEnd", dtmDateEnd) :
                new ObjectParameter("dtmDateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetMerchantStatement_Result>("Sp_GetMerchantStatement", merchant_fkParameter, dtmDateInitParameter, dtmDateEndParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_InsertCardHeader(Nullable<int> iD, Nullable<System.DateTime> dateadded, Nullable<int> merchant_fk, Nullable<decimal> order_total, Nullable<decimal> order_tax, Nullable<decimal> order_discount, Nullable<decimal> order_net, string orShipTo, string orShipAddress1, string orShipAddress2, string orShipCity, string orShipState, string orShipZipCode, string orShipCountry, string orShipPhone, string orRefNotes, Nullable<double> orTotalWeight, Nullable<int> orWeight_measureID, Nullable<int> deploymethID, Nullable<bool> fedExHomeDelivery, Nullable<bool> fedExSaturdayDelivery, Nullable<int> orShipType, Nullable<int> pmt_method, Nullable<double> orShipCost, string orComment, Nullable<int> agentID, string orShipEmail)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var dateaddedParameter = dateadded.HasValue ?
                new ObjectParameter("dateadded", dateadded) :
                new ObjectParameter("dateadded", typeof(System.DateTime));
    
            var merchant_fkParameter = merchant_fk.HasValue ?
                new ObjectParameter("merchant_fk", merchant_fk) :
                new ObjectParameter("merchant_fk", typeof(int));
    
            var order_totalParameter = order_total.HasValue ?
                new ObjectParameter("order_total", order_total) :
                new ObjectParameter("order_total", typeof(decimal));
    
            var order_taxParameter = order_tax.HasValue ?
                new ObjectParameter("order_tax", order_tax) :
                new ObjectParameter("order_tax", typeof(decimal));
    
            var order_discountParameter = order_discount.HasValue ?
                new ObjectParameter("order_discount", order_discount) :
                new ObjectParameter("order_discount", typeof(decimal));
    
            var order_netParameter = order_net.HasValue ?
                new ObjectParameter("order_net", order_net) :
                new ObjectParameter("order_net", typeof(decimal));
    
            var orShipToParameter = orShipTo != null ?
                new ObjectParameter("orShipTo", orShipTo) :
                new ObjectParameter("orShipTo", typeof(string));
    
            var orShipAddress1Parameter = orShipAddress1 != null ?
                new ObjectParameter("orShipAddress1", orShipAddress1) :
                new ObjectParameter("orShipAddress1", typeof(string));
    
            var orShipAddress2Parameter = orShipAddress2 != null ?
                new ObjectParameter("orShipAddress2", orShipAddress2) :
                new ObjectParameter("orShipAddress2", typeof(string));
    
            var orShipCityParameter = orShipCity != null ?
                new ObjectParameter("orShipCity", orShipCity) :
                new ObjectParameter("orShipCity", typeof(string));
    
            var orShipStateParameter = orShipState != null ?
                new ObjectParameter("orShipState", orShipState) :
                new ObjectParameter("orShipState", typeof(string));
    
            var orShipZipCodeParameter = orShipZipCode != null ?
                new ObjectParameter("orShipZipCode", orShipZipCode) :
                new ObjectParameter("orShipZipCode", typeof(string));
    
            var orShipCountryParameter = orShipCountry != null ?
                new ObjectParameter("orShipCountry", orShipCountry) :
                new ObjectParameter("orShipCountry", typeof(string));
    
            var orShipPhoneParameter = orShipPhone != null ?
                new ObjectParameter("orShipPhone", orShipPhone) :
                new ObjectParameter("orShipPhone", typeof(string));
    
            var orRefNotesParameter = orRefNotes != null ?
                new ObjectParameter("orRefNotes", orRefNotes) :
                new ObjectParameter("orRefNotes", typeof(string));
    
            var orTotalWeightParameter = orTotalWeight.HasValue ?
                new ObjectParameter("orTotalWeight", orTotalWeight) :
                new ObjectParameter("orTotalWeight", typeof(double));
    
            var orWeight_measureIDParameter = orWeight_measureID.HasValue ?
                new ObjectParameter("orWeight_measureID", orWeight_measureID) :
                new ObjectParameter("orWeight_measureID", typeof(int));
    
            var deploymethIDParameter = deploymethID.HasValue ?
                new ObjectParameter("deploymethID", deploymethID) :
                new ObjectParameter("deploymethID", typeof(int));
    
            var fedExHomeDeliveryParameter = fedExHomeDelivery.HasValue ?
                new ObjectParameter("FedExHomeDelivery", fedExHomeDelivery) :
                new ObjectParameter("FedExHomeDelivery", typeof(bool));
    
            var fedExSaturdayDeliveryParameter = fedExSaturdayDelivery.HasValue ?
                new ObjectParameter("FedExSaturdayDelivery", fedExSaturdayDelivery) :
                new ObjectParameter("FedExSaturdayDelivery", typeof(bool));
    
            var orShipTypeParameter = orShipType.HasValue ?
                new ObjectParameter("orShipType", orShipType) :
                new ObjectParameter("orShipType", typeof(int));
    
            var pmt_methodParameter = pmt_method.HasValue ?
                new ObjectParameter("pmt_method", pmt_method) :
                new ObjectParameter("pmt_method", typeof(int));
    
            var orShipCostParameter = orShipCost.HasValue ?
                new ObjectParameter("orShipCost", orShipCost) :
                new ObjectParameter("orShipCost", typeof(double));
    
            var orCommentParameter = orComment != null ?
                new ObjectParameter("orComment", orComment) :
                new ObjectParameter("orComment", typeof(string));
    
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var orShipEmailParameter = orShipEmail != null ?
                new ObjectParameter("orShipEmail", orShipEmail) :
                new ObjectParameter("orShipEmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_InsertCardHeader", iDParameter, dateaddedParameter, merchant_fkParameter, order_totalParameter, order_taxParameter, order_discountParameter, order_netParameter, orShipToParameter, orShipAddress1Parameter, orShipAddress2Parameter, orShipCityParameter, orShipStateParameter, orShipZipCodeParameter, orShipCountryParameter, orShipPhoneParameter, orRefNotesParameter, orTotalWeightParameter, orWeight_measureIDParameter, deploymethIDParameter, fedExHomeDeliveryParameter, fedExSaturdayDeliveryParameter, orShipTypeParameter, pmt_methodParameter, orShipCostParameter, orCommentParameter, agentIDParameter, orShipEmailParameter);
        }
    
        public virtual ObjectResult<SP_ippBrowser_Result> SP_ippBrowser(Nullable<int> agentid, Nullable<int> merchantid, Nullable<System.DateTime> ini_Date, Nullable<System.DateTime> end_Date, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            var ini_DateParameter = ini_Date.HasValue ?
                new ObjectParameter("ini_Date", ini_Date) :
                new ObjectParameter("ini_Date", typeof(System.DateTime));
    
            var end_DateParameter = end_Date.HasValue ?
                new ObjectParameter("end_Date", end_Date) :
                new ObjectParameter("end_Date", typeof(System.DateTime));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ippBrowser_Result>("SP_ippBrowser", agentidParameter, merchantidParameter, ini_DateParameter, end_DateParameter, emptyRecordParameter);
        }
    
        public virtual int sp_merchant_commisions(Nullable<int> merchant_fk, Nullable<int> agentId, Nullable<int> vendingType)
        {
            var merchant_fkParameter = merchant_fk.HasValue ?
                new ObjectParameter("merchant_fk", merchant_fk) :
                new ObjectParameter("merchant_fk", typeof(int));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(int));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_merchant_commisions", merchant_fkParameter, agentIdParameter, vendingTypeParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_report_balance_details_Result> sp_report_balance_details(Nullable<int> mid, Nullable<int> emptyRecord)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_balance_details_Result>("sp_report_balance_details", midParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_general_sales_summary_Result> sp_report_general_sales_summary(Nullable<int> agentid, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_general_sales_summary_Result>("sp_report_general_sales_summary", agentidParameter, ini_dateParameter, end_dateParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_general_sales_summary_dated_Result> sp_report_general_sales_summary_dated(Nullable<int> agentid, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_general_sales_summary_dated_Result>("sp_report_general_sales_summary_dated", agentidParameter, ini_dateParameter, end_dateParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_invoice_details_Result> sp_report_invoice_details(Nullable<int> inv_id, Nullable<int> emptyRecord)
        {
            var inv_idParameter = inv_id.HasValue ?
                new ObjectParameter("inv_id", inv_id) :
                new ObjectParameter("inv_id", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_invoice_details_Result>("sp_report_invoice_details", inv_idParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_Result> sp_report_msv_commission_details(Nullable<int> agentID, Nullable<System.DateTime> iniDate, Nullable<System.DateTime> endDate, Nullable<int> data_column, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var iniDateParameter = iniDate.HasValue ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var data_columnParameter = data_column.HasValue ?
                new ObjectParameter("data_column", data_column) :
                new ObjectParameter("data_column", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_Result>("sp_report_msv_commission_details", agentIDParameter, iniDateParameter, endDateParameter, data_columnParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_by_totals_Result> sp_report_msv_commission_details_by_totals(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_by_totals_Result>("sp_report_msv_commission_details_by_totals", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_from_amex_Result> sp_report_msv_commission_details_from_amex(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_from_amex_Result>("sp_report_msv_commission_details_from_amex", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_from_other_Result> sp_report_msv_commission_details_from_other(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_from_other_Result>("sp_report_msv_commission_details_from_other", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_from_visamc_Result> sp_report_msv_commission_details_from_visamc(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_from_visamc_Result>("sp_report_msv_commission_details_from_visamc", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_from_visamcBCK02062015_Result> sp_report_msv_commission_details_from_visamcBCK02062015(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_from_visamcBCK02062015_Result>("sp_report_msv_commission_details_from_visamcBCK02062015", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_details_from_visamcMine_Result> sp_report_msv_commission_details_from_visamcMine(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> columnID, Nullable<bool> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var columnIDParameter = columnID.HasValue ?
                new ObjectParameter("columnID", columnID) :
                new ObjectParameter("columnID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_details_from_visamcMine_Result>("sp_report_msv_commission_details_from_visamcMine", agentIDParameter, ini_dateParameter, end_dateParameter, columnIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_commission_summary_Result> sp_report_msv_commission_summary(Nullable<int> agentid, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_commission_summary_Result>("sp_report_msv_commission_summary", agentidParameter, ini_dateParameter, end_dateParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_portfolio_AccountsByType_Result> sp_report_msv_portfolio_AccountsByType(Nullable<int> agentid, Nullable<int> type)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_portfolio_AccountsByType_Result>("sp_report_msv_portfolio_AccountsByType", agentidParameter, typeParameter);
        }
    
        public virtual ObjectResult<sp_report_msv_portfolio_summary_Result> sp_report_msv_portfolio_summary(Nullable<int> agentid, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_msv_portfolio_summary_Result>("sp_report_msv_portfolio_summary", agentidParameter, emptyRecordParameter);
        }
    
        public virtual int sp_report_msv_portfolio_summary_general()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_report_msv_portfolio_summary_general");
        }
    
        public virtual ObjectResult<sp_report_prepaid_portfolio_inAlert_Result> sp_report_prepaid_portfolio_inAlert(Nullable<int> agentID, Nullable<int> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_prepaid_portfolio_inAlert_Result>("sp_report_prepaid_portfolio_inAlert", agentIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_sales_details_Result> sp_report_sales_details(Nullable<int> mid, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date, Nullable<int> emptyRecord)
        {
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_sales_details_Result>("sp_report_sales_details", midParameter, ini_dateParameter, end_dateParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_report_sales_invoice_details_Result> sp_report_sales_invoice_details(Nullable<int> inv_id, Nullable<int> emptyRecord)
        {
            var inv_idParameter = inv_id.HasValue ?
                new ObjectParameter("inv_id", inv_id) :
                new ObjectParameter("inv_id", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_sales_invoice_details_Result>("sp_report_sales_invoice_details", inv_idParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_retrieve_documents_Result> sp_retrieve_documents(Nullable<bool> emptyRecord)
        {
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retrieve_documents_Result>("sp_retrieve_documents", emptyRecordParameter);
        }
    
        public virtual ObjectResult<sp_retrieve_incidents_Result> sp_retrieve_incidents(Nullable<int> agent_id, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date)
        {
            var agent_idParameter = agent_id.HasValue ?
                new ObjectParameter("agent_id", agent_id) :
                new ObjectParameter("agent_id", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retrieve_incidents_Result>("sp_retrieve_incidents", agent_idParameter, ini_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<sp_retrieve_leads_Result> sp_retrieve_leads(Nullable<int> agentid, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retrieve_leads_Result>("sp_retrieve_leads", agentidParameter, ini_dateParameter, end_dateParameter);
        }
    
        public virtual ObjectResult<sp_retrieve_parameters_Result> sp_retrieve_parameters(string procedure_name)
        {
            var procedure_nameParameter = procedure_name != null ?
                new ObjectParameter("procedure_name", procedure_name) :
                new ObjectParameter("procedure_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_retrieve_parameters_Result>("sp_retrieve_parameters", procedure_nameParameter);
        }
    
        public virtual ObjectResult<string> sp_retrieve_spNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_retrieve_spNames");
        }
    
        public virtual ObjectResult<string> sp_retrieve_storedprocedure_columns(string spname)
        {
            var spnameParameter = spname != null ?
                new ObjectParameter("spname", spname) :
                new ObjectParameter("spname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_retrieve_storedprocedure_columns", spnameParameter);
        }
    
        public virtual ObjectResult<SP_ShowAccountRegister_Result> SP_ShowAccountRegister(Nullable<int> reportType, Nullable<int> codeID, string iniDate, string endDate)
        {
            var reportTypeParameter = reportType.HasValue ?
                new ObjectParameter("reportType", reportType) :
                new ObjectParameter("reportType", typeof(int));
    
            var codeIDParameter = codeID.HasValue ?
                new ObjectParameter("codeID", codeID) :
                new ObjectParameter("codeID", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ShowAccountRegister_Result>("SP_ShowAccountRegister", reportTypeParameter, codeIDParameter, iniDateParameter, endDateParameter);
        }
    
        public virtual int sp_update_user_password(Nullable<int> user_id, string password)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_user_password", user_idParameter, passwordParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Sp_WEB_POS_Merchant_GetTransactions_AgentGroup(Nullable<int> agentid, Nullable<int> mid, string iniDate, string endDate, string trxType_hyp_fk, string item_fk, Nullable<int> vendingType, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var midParameter = mid.HasValue ?
                new ObjectParameter("mid", mid) :
                new ObjectParameter("mid", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var trxType_hyp_fkParameter = trxType_hyp_fk != null ?
                new ObjectParameter("TrxType_hyp_fk", trxType_hyp_fk) :
                new ObjectParameter("TrxType_hyp_fk", typeof(string));
    
            var item_fkParameter = item_fk != null ?
                new ObjectParameter("item_fk", item_fk) :
                new ObjectParameter("item_fk", typeof(string));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_WEB_POS_Merchant_GetTransactions_AgentGroup", agentidParameter, midParameter, iniDateParameter, endDateParameter, trxType_hyp_fkParameter, item_fkParameter, vendingTypeParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<Test_Result> Test()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Test_Result>("Test");
        }
    
        public virtual ObjectResult<get_user_Result> get_user(string userid, string passCredential)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var passCredentialParameter = passCredential != null ?
                new ObjectParameter("passCredential", passCredential) :
                new ObjectParameter("passCredential", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_user_Result>("get_user", useridParameter, passCredentialParameter);
        }
    
        public virtual ObjectResult<sp_report_portfolio_summary_Result> sp_report_portfolio_summary(Nullable<int> agentID, Nullable<int> emptyRecord)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_portfolio_summary_Result>("sp_report_portfolio_summary", agentIDParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<SP_Fullcarga_Statetement_Result> SP_Fullcarga_Statetement(Nullable<System.DateTime> datei, Nullable<System.DateTime> dateF, Nullable<int> uniqueId)
        {
            var dateiParameter = datei.HasValue ?
                new ObjectParameter("Datei", datei) :
                new ObjectParameter("Datei", typeof(System.DateTime));
    
            var dateFParameter = dateF.HasValue ?
                new ObjectParameter("DateF", dateF) :
                new ObjectParameter("DateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Fullcarga_Statetement_Result>("SP_Fullcarga_Statetement", dateiParameter, dateFParameter, uniqueIdParameter);
        }
    
        public virtual ObjectResult<SP_Fullcarga_PrepaidSalesSummary_Result> SP_Fullcarga_PrepaidSalesSummary(Nullable<System.DateTime> datei, Nullable<System.DateTime> dateF, Nullable<int> uniqueId, Nullable<int> isMerchant)
        {
            var dateiParameter = datei.HasValue ?
                new ObjectParameter("Datei", datei) :
                new ObjectParameter("Datei", typeof(System.DateTime));
    
            var dateFParameter = dateF.HasValue ?
                new ObjectParameter("DateF", dateF) :
                new ObjectParameter("DateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            var isMerchantParameter = isMerchant.HasValue ?
                new ObjectParameter("isMerchant", isMerchant) :
                new ObjectParameter("isMerchant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Fullcarga_PrepaidSalesSummary_Result>("SP_Fullcarga_PrepaidSalesSummary", dateiParameter, dateFParameter, uniqueIdParameter, isMerchantParameter);
        }
    
        public virtual ObjectResult<SP_Fullcarga_DetailInvoice_Result> SP_Fullcarga_DetailInvoice(Nullable<int> parInvId, Nullable<int> uniqueId)
        {
            var parInvIdParameter = parInvId.HasValue ?
                new ObjectParameter("ParInvId", parInvId) :
                new ObjectParameter("ParInvId", typeof(int));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Fullcarga_DetailInvoice_Result>("SP_Fullcarga_DetailInvoice", parInvIdParameter, uniqueIdParameter);
        }
    
        public virtual ObjectResult<sp_GetMerchantCommissionsProfile_Result> sp_GetMerchantCommissionsProfile(Nullable<int> merchant_fk, Nullable<int> agentId, Nullable<int> vendingType)
        {
            var merchant_fkParameter = merchant_fk.HasValue ?
                new ObjectParameter("merchant_fk", merchant_fk) :
                new ObjectParameter("merchant_fk", typeof(int));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(int));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMerchantCommissionsProfile_Result>("sp_GetMerchantCommissionsProfile", merchant_fkParameter, agentIdParameter, vendingTypeParameter);
        }
    
        public virtual ObjectResult<Sp_TransactionsSummary_Result> Sp_TransactionsSummary(Nullable<System.DateTime> datei, Nullable<System.DateTime> dateF, Nullable<int> uniqueId, Nullable<int> isMerchant)
        {
            var dateiParameter = datei.HasValue ?
                new ObjectParameter("Datei", datei) :
                new ObjectParameter("Datei", typeof(System.DateTime));
    
            var dateFParameter = dateF.HasValue ?
                new ObjectParameter("DateF", dateF) :
                new ObjectParameter("DateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            var isMerchantParameter = isMerchant.HasValue ?
                new ObjectParameter("isMerchant", isMerchant) :
                new ObjectParameter("isMerchant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TransactionsSummary_Result>("Sp_TransactionsSummary", dateiParameter, dateFParameter, uniqueIdParameter, isMerchantParameter);
        }
    
        public virtual int sp_GetMerchantCreditLimits(Nullable<int> agentId, Nullable<bool> emptyRecord, Nullable<int> merchant_id)
        {
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            var merchant_idParameter = merchant_id.HasValue ?
                new ObjectParameter("merchant_id", merchant_id) :
                new ObjectParameter("merchant_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetMerchantCreditLimits", agentIdParameter, emptyRecordParameter, merchant_idParameter);
        }
    
        public virtual ObjectResult<GetMerchantCreditLimits_Result> GetMerchantCreditLimits(Nullable<int> agentId, Nullable<int> merchantId, Nullable<bool> emptyRecord)
        {
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("AgentId", agentId) :
                new ObjectParameter("AgentId", typeof(int));
    
            var merchantIdParameter = merchantId.HasValue ?
                new ObjectParameter("merchantId", merchantId) :
                new ObjectParameter("merchantId", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMerchantCreditLimits_Result>("GetMerchantCreditLimits", agentIdParameter, merchantIdParameter, emptyRecordParameter);
        }
    
        public virtual int sp_FullCarga_change_credit_limit(Nullable<int> parMid, Nullable<decimal> parNewCL, Nullable<decimal> parNewDailyCL)
        {
            var parMidParameter = parMid.HasValue ?
                new ObjectParameter("parMid", parMid) :
                new ObjectParameter("parMid", typeof(int));
    
            var parNewCLParameter = parNewCL.HasValue ?
                new ObjectParameter("parNewCL", parNewCL) :
                new ObjectParameter("parNewCL", typeof(decimal));
    
            var parNewDailyCLParameter = parNewDailyCL.HasValue ?
                new ObjectParameter("parNewDailyCL", parNewDailyCL) :
                new ObjectParameter("parNewDailyCL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FullCarga_change_credit_limit", parMidParameter, parNewCLParameter, parNewDailyCLParameter);
        }
    
        public virtual ObjectResult<SP_Fullcarga_DetailInvoicebck_Result> SP_Fullcarga_DetailInvoicebck(Nullable<int> parInvId, Nullable<int> uniqueId)
        {
            var parInvIdParameter = parInvId.HasValue ?
                new ObjectParameter("ParInvId", parInvId) :
                new ObjectParameter("ParInvId", typeof(int));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Fullcarga_DetailInvoicebck_Result>("SP_Fullcarga_DetailInvoicebck", parInvIdParameter, uniqueIdParameter);
        }
    
        public virtual ObjectResult<Sp_TransactionsSummaryBCK_Result> Sp_TransactionsSummaryBCK(Nullable<int> isoId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var isoIdParameter = isoId.HasValue ?
                new ObjectParameter("isoId", isoId) :
                new ObjectParameter("isoId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TransactionsSummaryBCK_Result>("Sp_TransactionsSummaryBCK", isoIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int sp_FullCarga_change_status(Nullable<int> parMid, Nullable<int> parisActive)
        {
            var parMidParameter = parMid.HasValue ?
                new ObjectParameter("parMid", parMid) :
                new ObjectParameter("parMid", typeof(int));
    
            var parisActiveParameter = parisActive.HasValue ?
                new ObjectParameter("parisActive", parisActive) :
                new ObjectParameter("parisActive", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_FullCarga_change_status", parMidParameter, parisActiveParameter);
        }
    
        public virtual ObjectResult<SP_Fullcarga_DetailInvoice_with_hrf_Result> SP_Fullcarga_DetailInvoice_with_hrf(Nullable<int> parInvId, Nullable<int> uniqueId)
        {
            var parInvIdParameter = parInvId.HasValue ?
                new ObjectParameter("ParInvId", parInvId) :
                new ObjectParameter("ParInvId", typeof(int));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Fullcarga_DetailInvoice_with_hrf_Result>("SP_Fullcarga_DetailInvoice_with_hrf", parInvIdParameter, uniqueIdParameter);
        }
    
        public virtual int Sp_get_Today_Transactions_with_Credits(Nullable<int> agentid, Nullable<int> merchantid, string iniDate, string endDate, string trxType_hyp_fk, string item_fk, Nullable<int> vendingType, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var trxType_hyp_fkParameter = trxType_hyp_fk != null ?
                new ObjectParameter("TrxType_hyp_fk", trxType_hyp_fk) :
                new ObjectParameter("TrxType_hyp_fk", typeof(string));
    
            var item_fkParameter = item_fk != null ?
                new ObjectParameter("item_fk", item_fk) :
                new ObjectParameter("item_fk", typeof(string));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_get_Today_Transactions_with_Credits", agentidParameter, merchantidParameter, iniDateParameter, endDateParameter, trxType_hyp_fkParameter, item_fkParameter, vendingTypeParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<Sp_TransactionsSummary_new_Result> Sp_TransactionsSummary_new(Nullable<System.DateTime> datei, Nullable<System.DateTime> dateF, Nullable<int> uniqueId, Nullable<int> isMerchant)
        {
            var dateiParameter = datei.HasValue ?
                new ObjectParameter("Datei", datei) :
                new ObjectParameter("Datei", typeof(System.DateTime));
    
            var dateFParameter = dateF.HasValue ?
                new ObjectParameter("DateF", dateF) :
                new ObjectParameter("DateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            var isMerchantParameter = isMerchant.HasValue ?
                new ObjectParameter("isMerchant", isMerchant) :
                new ObjectParameter("isMerchant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_TransactionsSummary_new_Result>("Sp_TransactionsSummary_new", dateiParameter, dateFParameter, uniqueIdParameter, isMerchantParameter);
        }
    
        public virtual ObjectResult<GetTodayTransactions_New_Result> GetTodayTransactions_New(Nullable<int> agentid, Nullable<int> merchantid, string iniDate, string endDate, string trxType_hyp_fk, string item_fk, Nullable<int> vendingType, Nullable<bool> emptyRecord)
        {
            var agentidParameter = agentid.HasValue ?
                new ObjectParameter("agentid", agentid) :
                new ObjectParameter("agentid", typeof(int));
    
            var merchantidParameter = merchantid.HasValue ?
                new ObjectParameter("merchantid", merchantid) :
                new ObjectParameter("merchantid", typeof(int));
    
            var iniDateParameter = iniDate != null ?
                new ObjectParameter("iniDate", iniDate) :
                new ObjectParameter("iniDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(string));
    
            var trxType_hyp_fkParameter = trxType_hyp_fk != null ?
                new ObjectParameter("TrxType_hyp_fk", trxType_hyp_fk) :
                new ObjectParameter("TrxType_hyp_fk", typeof(string));
    
            var item_fkParameter = item_fk != null ?
                new ObjectParameter("item_fk", item_fk) :
                new ObjectParameter("item_fk", typeof(string));
    
            var vendingTypeParameter = vendingType.HasValue ?
                new ObjectParameter("vendingType", vendingType) :
                new ObjectParameter("vendingType", typeof(int));
    
            var emptyRecordParameter = emptyRecord.HasValue ?
                new ObjectParameter("emptyRecord", emptyRecord) :
                new ObjectParameter("emptyRecord", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTodayTransactions_New_Result>("GetTodayTransactions_New", agentidParameter, merchantidParameter, iniDateParameter, endDateParameter, trxType_hyp_fkParameter, item_fkParameter, vendingTypeParameter, emptyRecordParameter);
        }
    
        public virtual ObjectResult<SP_Send_CommissionReport_Result> SP_Send_CommissionReport(Nullable<System.DateTime> rundateI, Nullable<System.DateTime> rundateF, Nullable<int> uniqueId, Nullable<int> isMerchant)
        {
            var rundateIParameter = rundateI.HasValue ?
                new ObjectParameter("RundateI", rundateI) :
                new ObjectParameter("RundateI", typeof(System.DateTime));
    
            var rundateFParameter = rundateF.HasValue ?
                new ObjectParameter("RundateF", rundateF) :
                new ObjectParameter("RundateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            var isMerchantParameter = isMerchant.HasValue ?
                new ObjectParameter("isMerchant", isMerchant) :
                new ObjectParameter("isMerchant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Send_CommissionReport_Result>("SP_Send_CommissionReport", rundateIParameter, rundateFParameter, uniqueIdParameter, isMerchantParameter);
        }
    
        public virtual ObjectResult<SP_Send_AgentToBillMerchants_Result> SP_Send_AgentToBillMerchants(Nullable<System.DateTime> rundateI, Nullable<System.DateTime> rundateF, Nullable<int> uniqueId)
        {
            var rundateIParameter = rundateI.HasValue ?
                new ObjectParameter("RundateI", rundateI) :
                new ObjectParameter("RundateI", typeof(System.DateTime));
    
            var rundateFParameter = rundateF.HasValue ?
                new ObjectParameter("RundateF", rundateF) :
                new ObjectParameter("RundateF", typeof(System.DateTime));
    
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("UniqueId", uniqueId) :
                new ObjectParameter("UniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Send_AgentToBillMerchants_Result>("SP_Send_AgentToBillMerchants", rundateIParameter, rundateFParameter, uniqueIdParameter);
        }
    
        public virtual int sp_update_information(Nullable<int> parUniqueId, Nullable<int> parIsmerchant, string parEmail, string parPhone)
        {
            var parUniqueIdParameter = parUniqueId.HasValue ?
                new ObjectParameter("parUniqueId", parUniqueId) :
                new ObjectParameter("parUniqueId", typeof(int));
    
            var parIsmerchantParameter = parIsmerchant.HasValue ?
                new ObjectParameter("parIsmerchant", parIsmerchant) :
                new ObjectParameter("parIsmerchant", typeof(int));
    
            var parEmailParameter = parEmail != null ?
                new ObjectParameter("parEmail", parEmail) :
                new ObjectParameter("parEmail", typeof(string));
    
            var parPhoneParameter = parPhone != null ?
                new ObjectParameter("parPhone", parPhone) :
                new ObjectParameter("parPhone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_information", parUniqueIdParameter, parIsmerchantParameter, parEmailParameter, parPhoneParameter);
        }
    
        public virtual int sp_update_virtualoffice_commission(Nullable<int> parMerchant, Nullable<int> parProducSbt, Nullable<decimal> merchantcomm, Nullable<decimal> agentComm, Nullable<decimal> distComm, Nullable<decimal> isoComm)
        {
            var parMerchantParameter = parMerchant.HasValue ?
                new ObjectParameter("parMerchant", parMerchant) :
                new ObjectParameter("parMerchant", typeof(int));
    
            var parProducSbtParameter = parProducSbt.HasValue ?
                new ObjectParameter("parProducSbt", parProducSbt) :
                new ObjectParameter("parProducSbt", typeof(int));
    
            var merchantcommParameter = merchantcomm.HasValue ?
                new ObjectParameter("merchantcomm", merchantcomm) :
                new ObjectParameter("merchantcomm", typeof(decimal));
    
            var agentCommParameter = agentComm.HasValue ?
                new ObjectParameter("AgentComm", agentComm) :
                new ObjectParameter("AgentComm", typeof(decimal));
    
            var distCommParameter = distComm.HasValue ?
                new ObjectParameter("DistComm", distComm) :
                new ObjectParameter("DistComm", typeof(decimal));
    
            var isoCommParameter = isoComm.HasValue ?
                new ObjectParameter("IsoComm", isoComm) :
                new ObjectParameter("IsoComm", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_virtualoffice_commission", parMerchantParameter, parProducSbtParameter, merchantcommParameter, agentCommParameter, distCommParameter, isoCommParameter);
        }
    
        public virtual ObjectResult<sp_child_list_by_agent_Result> sp_child_list_by_agent(Nullable<int> uniqueId)
        {
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("uniqueId", uniqueId) :
                new ObjectParameter("uniqueId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_child_list_by_agent_Result>("sp_child_list_by_agent", uniqueIdParameter);
        }
    
        public virtual ObjectResult<sp_list_products_related_Result> sp_list_products_related(Nullable<int> uniqueId, Nullable<int> isMerchant)
        {
            var uniqueIdParameter = uniqueId.HasValue ?
                new ObjectParameter("uniqueId", uniqueId) :
                new ObjectParameter("uniqueId", typeof(int));
    
            var isMerchantParameter = isMerchant.HasValue ?
                new ObjectParameter("IsMerchant", isMerchant) :
                new ObjectParameter("IsMerchant", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_list_products_related_Result>("sp_list_products_related", uniqueIdParameter, isMerchantParameter);
        }
    
        public virtual int sp_update_commission_virtualOffice(Nullable<int> fatherId, Nullable<int> childId, Nullable<int> isChildMerchant, Nullable<int> product_sbt, Nullable<decimal> commissionChange)
        {
            var fatherIdParameter = fatherId.HasValue ?
                new ObjectParameter("FatherId", fatherId) :
                new ObjectParameter("FatherId", typeof(int));
    
            var childIdParameter = childId.HasValue ?
                new ObjectParameter("ChildId", childId) :
                new ObjectParameter("ChildId", typeof(int));
    
            var isChildMerchantParameter = isChildMerchant.HasValue ?
                new ObjectParameter("IsChildMerchant", isChildMerchant) :
                new ObjectParameter("IsChildMerchant", typeof(int));
    
            var product_sbtParameter = product_sbt.HasValue ?
                new ObjectParameter("product_sbt", product_sbt) :
                new ObjectParameter("product_sbt", typeof(int));
    
            var commissionChangeParameter = commissionChange.HasValue ?
                new ObjectParameter("CommissionChange", commissionChange) :
                new ObjectParameter("CommissionChange", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_commission_virtualOffice", fatherIdParameter, childIdParameter, isChildMerchantParameter, product_sbtParameter, commissionChangeParameter);
        }
    
        public virtual ObjectResult<sp_report_portfolio_summary_totals_Result> sp_report_portfolio_summary_totals(Nullable<int> agentID, Nullable<System.DateTime> ini_date, Nullable<System.DateTime> end_date)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(int));
    
            var ini_dateParameter = ini_date.HasValue ?
                new ObjectParameter("ini_date", ini_date) :
                new ObjectParameter("ini_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_report_portfolio_summary_totals_Result>("sp_report_portfolio_summary_totals", agentIDParameter, ini_dateParameter, end_dateParameter);
        }
    
        public virtual int SP_Create_PosPendingMerchants(string businessName, string businessPhone, string businessFax, string dBA, string emailAddress, string cellularNumber, string businessStreet, string businessCity, string businessState, string businessZip, string merchant_MainContactPhone, string merchant_MainContact, Nullable<int> merchant_RepId, string repName)
        {
            var businessNameParameter = businessName != null ?
                new ObjectParameter("BusinessName", businessName) :
                new ObjectParameter("BusinessName", typeof(string));
    
            var businessPhoneParameter = businessPhone != null ?
                new ObjectParameter("BusinessPhone", businessPhone) :
                new ObjectParameter("BusinessPhone", typeof(string));
    
            var businessFaxParameter = businessFax != null ?
                new ObjectParameter("BusinessFax", businessFax) :
                new ObjectParameter("BusinessFax", typeof(string));
    
            var dBAParameter = dBA != null ?
                new ObjectParameter("DBA", dBA) :
                new ObjectParameter("DBA", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            var cellularNumberParameter = cellularNumber != null ?
                new ObjectParameter("CellularNumber", cellularNumber) :
                new ObjectParameter("CellularNumber", typeof(string));
    
            var businessStreetParameter = businessStreet != null ?
                new ObjectParameter("BusinessStreet", businessStreet) :
                new ObjectParameter("BusinessStreet", typeof(string));
    
            var businessCityParameter = businessCity != null ?
                new ObjectParameter("BusinessCity", businessCity) :
                new ObjectParameter("BusinessCity", typeof(string));
    
            var businessStateParameter = businessState != null ?
                new ObjectParameter("BusinessState", businessState) :
                new ObjectParameter("BusinessState", typeof(string));
    
            var businessZipParameter = businessZip != null ?
                new ObjectParameter("BusinessZip", businessZip) :
                new ObjectParameter("BusinessZip", typeof(string));
    
            var merchant_MainContactPhoneParameter = merchant_MainContactPhone != null ?
                new ObjectParameter("Merchant_MainContactPhone", merchant_MainContactPhone) :
                new ObjectParameter("Merchant_MainContactPhone", typeof(string));
    
            var merchant_MainContactParameter = merchant_MainContact != null ?
                new ObjectParameter("Merchant_MainContact", merchant_MainContact) :
                new ObjectParameter("Merchant_MainContact", typeof(string));
    
            var merchant_RepIdParameter = merchant_RepId.HasValue ?
                new ObjectParameter("Merchant_RepId", merchant_RepId) :
                new ObjectParameter("Merchant_RepId", typeof(int));
    
            var repNameParameter = repName != null ?
                new ObjectParameter("RepName", repName) :
                new ObjectParameter("RepName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_PosPendingMerchants", businessNameParameter, businessPhoneParameter, businessFaxParameter, dBAParameter, emailAddressParameter, cellularNumberParameter, businessStreetParameter, businessCityParameter, businessStateParameter, businessZipParameter, merchant_MainContactPhoneParameter, merchant_MainContactParameter, merchant_RepIdParameter, repNameParameter);
        }
    }
}
