//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOfficeToolManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredefinedFilter
    {
        public PredefinedFilter()
        {
            this.ReportPredefinedFilterRels = new HashSet<ReportPredefinedFilterRel>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime TimeSpan { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int Type { get; set; }
        public string ColumnName { get; set; }
        public string ParameterName { get; set; }
    
        public virtual ICollection<ReportPredefinedFilterRel> ReportPredefinedFilterRels { get; set; }
    }
}
