//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOfficeToolManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportLabel
    {
        public int Id { get; set; }
        public string ColumnName { get; set; }
        public string Label { get; set; }
        public byte[] RowVersion { get; set; }
        public System.DateTime TimeSpan { get; set; }
        public int ReportId { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
