//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualOfficeToolManager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class VirtualOfficeEntities : DbContext
    {
        public VirtualOfficeEntities()
            : base("name=VirtualOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<ApiUser> ApiUsers { get; set; }
        public DbSet<PredefinedFilter> PredefinedFilters { get; set; }
        public DbSet<ReportPredefinedFilterRel> ReportPredefinedFilterRels { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<ReportToReportRel> ReportToReportRels { get; set; }
        public DbSet<ReportUserFilterRel> ReportUserFilterRels { get; set; }
        public DbSet<Sql_HtmlTypeNameMappings> Sql_HtmlTypeNameMappings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<UserFilter> UserFilters { get; set; }
        public DbSet<UserReport> UserReports { get; set; }
        public DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<string> sp_retrieve_spNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_retrieve_spNames");
        }
    }
}
