// <auto-generated />
namespace CoreData.PindataMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class config5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(config5));
        
        string IMigrationMetadata.Id
        {
            get { return "201408121525163_config5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
